//
//  UUIDExtern.h
//  Konashi
//
//  Created by Akira Matsuda on 9/20/14.
//  Copyright (c) 2014 Akira Matsuda. All rights reserved.
//

#ifndef Konashi_UUIDExtern_h
#define Konashi_UUIDExtern_h

#import "KNSUUID.h"

#pragma mark - Konashi UUID

extern KNSUUID KONASHI_BATT_SERVICE_UUID;
extern KNSUUID KONASHI_LEVEL_SERVICE_UUID;
extern KNSUUID KONASHI_POWER_STATE_UUID;

/***************************
 KONASHI GATT DB
 ****************************/

extern KNSUUID KONASHI_SERVICE_UUID;
// PIO
extern KNSUUID KONASHI_PIO_SETTING_UUID;
extern KNSUUID KONASHI_PIO_PULLUP_UUID;
extern KNSUUID KONASHI_PIO_OUTPUT_UUID;
extern KNSUUID KONASHI_PIO_INPUT_NOTIFICATION_UUID;

// PWM
extern KNSUUID KONASHI_PWM_CONFIG_UUID;
extern KNSUUID KONASHI_PWM_PARAM_UUID;
extern KNSUUID KONASHI_PWM_DUTY_UUID;

// Analog
extern KNSUUID KONASHI_ANALOG_DRIVE_UUID;
extern KNSUUID KONASHI_ANALOG_READ0_UUID;
extern KNSUUID KONASHI_ANALOG_READ1_UUID;
extern KNSUUID KONASHI_ANALOG_READ2_UUID;

// I2C
extern KNSUUID KONASHI_I2C_CONFIG_UUID;
extern KNSUUID KONASHI_I2C_START_STOP_UUID;
extern KNSUUID KONASHI_I2C_WRITE_UUID;
extern KNSUUID KONASHI_I2C_READ_PARAM_UIUD;
extern KNSUUID KONASHI_I2C_READ_UUID;

// UART
extern KNSUUID KONASHI_UART_CONFIG_UUID;
extern KNSUUID KONASHI_UART_BAUDRATE_UUID;
extern KNSUUID KONASHI_UART_TX_UUID;
extern KNSUUID KONASHI_UART_RX_NOTIFICATION_UUID;

// Hardware
extern KNSUUID KONASHI_HARDWARE_RESET_UUID;
extern KNSUUID KONASHI_HARDWARE_LOW_BAT_NOTIFICATION_UUID;

#pragma mark - Koshian UUID

extern KNSUUID KOSHIAN_BATT_SERVICE_UUID;
extern KNSUUID KOSHIAN_LEVEL_SERVICE_UUID;
extern KNSUUID KOSHIAN_POWER_STATE_UUID;

/***************************
 KOSHIAN GATT DB
 ****************************/

extern KNSUUID KOSHIAN_SERVICE_UUID;
// PIO
extern KNSUUID KOSHIAN_PIO_SETTING_UUID;
extern KNSUUID KOSHIAN_PIO_PULLUP_UUID;
extern KNSUUID KOSHIAN_PIO_OUTPUT_UUID;
extern KNSUUID KOSHIAN_PIO_INPUT_NOTIFICATION_UUID;

// PWM
extern KNSUUID KOSHIAN_PWM_CONFIG_UUID;
extern KNSUUID KOSHIAN_PWM_PARAM_UUID;
extern KNSUUID KOSHIAN_PWM_DUTY_UUID;

// Analog
extern KNSUUID KOSHIAN_ANALOG_DRIVE_UUID;
extern KNSUUID KOSHIAN_ANALOG_READ0_UUID;
extern KNSUUID KOSHIAN_ANALOG_READ1_UUID;
extern KNSUUID KOSHIAN_ANALOG_READ2_UUID;

// I2C
extern KNSUUID KOSHIAN_I2C_CONFIG_UUID;
extern KNSUUID KOSHIAN_I2C_START_STOP_UUID;
extern KNSUUID KOSHIAN_I2C_WRITE_UUID;
extern KNSUUID KOSHIAN_I2C_READ_PARAM_UIUD;
extern KNSUUID KOSHIAN_I2C_READ_UUID;

// UART
extern KNSUUID KOSHIAN_UART_CONFIG_UUID;
extern KNSUUID KOSHIAN_UART_BAUDRATE_UUID;
extern KNSUUID KOSHIAN_UART_TX_UUID;
extern KNSUUID KOSHIAN_UART_RX_NOTIFICATION_UUID;

// Hardware
extern KNSUUID KOSHIAN_HARDWARE_RESET_UUID;
extern KNSUUID KOSHIAN_HARDWARE_LOW_BAT_NOTIFICATION_UUID;


extern KNSUUID KOSHIAN_UUID_WS_UPGRADE_SERVICE;
extern KNSUUID KOSHIAN_UUID_WS_UPGRADE_CHARACTERISTIC_CONTROL_POINT;
extern KNSUUID KOSHIAN_UUID_WS_UPGRADE_CHARACTERISTIC_DATA;

#endif
